### ISSUE TITLE
Replace {!!  with {{ inside show_field

### ISSUE THREAD

**Issue by tad3j** [InfyOmLabs/adminlte-templates#18]
I've noticed that by default data from DB is not escaped inside [show_field.stub#L4](https://github.com/InfyOmLabs/adminlte-templates/blob/develop/templates/scaffold/views/show_field.stub#L4).

Wouldn't it be better/safer to always escape the data and let developers change it only if needed?

**Comment by ajayinfyom** [comment]
Fixed
