### ISSUE TITLE
Pagination missing in index.stub

### ISSUE THREAD

**Issue by alexglue** [InfyOmLabs/adminlte-templates#2]
pagination is missing by default. You should to add "$PAGINATE$" to /scaffold/index.stub

**Comment by lucasprogamer** [comment]
some solution?

**Comment by jkm-droid** [comment]
can someone please send a code of paginating results from datatables generated usin infyomlabs??

**Comment by mitulgolakiya** [comment]
@jkmchinoxxx datatable pagination should not be part of this issue. Datatable generates its pagination by itself.

@jkmchinoxxx specify the problem that you are facing and we can check it.
