### ISSUE TITLE
Sidebar menu and sidebar toggle not working

### ISSUE THREAD

**Issue by kmligue** [InfyOmLabs/adminlte-templates#28]
Sidebar menu is not expanding and sidebar toggle not working.

**Comment by ShaileshInfyom** [comment]
which laravel  version you have used?

**Comment by kmligue** [comment]
version 5.5

**Comment by ShaileshInfyom** [comment]
please follow this [doc](http://labs.infyom.com/laravelgenerator/docs/master/adminlte-templates) may be helpfull
because with 5.5 working fine for me. i have recently used. 
Thanks

**Comment by ShaileshInfyom** [comment]
also clone this [boilerplate ](https://github.com/InfyOmLabs/adminlte-generator) and match your code what's going wrong.

**Comment by kmligue** [comment]
got mine working by updating some of the attribute from the header and sidebar elements

From
`<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
To
`<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`

From
`<ul class="sidebar-menu">`
To
`<ul class="sidebar-menu" data-widget="tree">`

**Comment by joeedman** [comment]
Great! This work for me! Thanks!

**Comment by afzallogicalwings** [comment]
thanks kmligue  for this answare and it is working on mobile device but creates another issue in window view

**Comment by nouman103** [comment]
> got mine working by updating some of the attribute from the header and sidebar elements
> 
> From
> `<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
> To
> `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`
> 
> From
> `<ul class="sidebar-menu">`
> To
> `<ul class="sidebar-menu" data-widget="tree">`

Toggle is working for me but sidebar completely disappear.

**Comment by ShaileshInfyom** [comment]
@nouman103 
> > got mine working by updating some of the attribute from the header and sidebar elements
> > From
> > `<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
> > To
> > `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`
> > From
> > `<ul class="sidebar-menu">`
> > To
> > `<ul class="sidebar-menu" data-widget="tree">`
> 
> Toggle is working for me but sidebar completely disappear.

Which version are you using?
