### ISSUE TITLE
Format Date Issue

### ISSUE THREAD

**Issue by erbaafidotama** [InfyOmLabs/adminlte-templates#54]
I have field date. When i try to choose date, always reset. I just want to pick date, not date picker and i want format DD/MM/YYYY. How resolve this problem?

`@section('scripts')
    <script type="text/javascript">
        $('#tgl_lahir').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection`

Thx

**Comment by ajayinfyom** [comment]
issue fixed.
