### ISSUE TITLE
What's the difference of table.stub and blade_table_body.stub?

### ISSUE THREAD

**Issue by skys215** [InfyOmLabs/adminlte-templates#58]
Hi, I'm confused about this two files, it seems that only `id` is added to the blade_table_body. 

What's the intention of having two different stub file to make a table if difference is just  `id` on the attribute?

**Comment by ajayinfyom** [comment]
@skys215 Basically both files are the same. On starting phase of a generator we are using `table.stub`, but now no longer use that file. we use only  `blade_table_body.stud`.  will remove one file.

**Comment by skys215** [comment]
Ok, I got it. Thanks.
