### ISSUE TITLE
Support Adminlte3 Version

### ISSUE THREAD

**Issue by hirenbhut93** [InfyOmLabs/adminlte-templates#60]

**Comment by mitulgolakiya** [comment]
We will consider it to add that once we got time. Otherwise, you can fork the templates and open a PR for that.

**Comment by horaciod** [comment]
anyone working on this  ?

**Comment by mitulgolakiya** [comment]
@horaciod we have just started working on this.

**Comment by farsheel** [comment]
is there anyway to try this? which branch you guys are working

**Comment by mitulgolakiya** [comment]
We are working in `mitul/v3`, but we are doing some major refactoring. so I will advise that you do not fork that and put any PR for that.

**Comment by peterson-umoke** [comment]
> We are working in `mitul/v3`, but we are doing some major refactoring. so I will advise that you do not fork that and put any PR for that.

Finally, bs4 is coming....

**Comment by mitulgolakiya** [comment]
Finally added it. I would love to hear feedbacks from all of you. @hirenbhut93 @horaciod @farsheel @peterson-umoke

**Comment by peterson-umoke** [comment]
@mitulgolakiya ok
