### ISSUE TITLE
Problem I Think CSS

### ISSUE THREAD

**Issue by hunterbit** [InfyOmLabs/adminlte-templates#67]
Hi to all,
I have problem when I use select2 plugin.
My select I view not very well.
This picture of the problem

![image](https://user-images.githubusercontent.com/3189486/106339756-d8b11600-6297-11eb-93af-e360fee47af1.png)

How I can resolve it?

**Comment by ShaileshInfyom** [comment]
@hunterbit you can set the hight or hight for fix the issue
