### ISSUE TITLE
[Bug]: View [backend.layouts.datatables_css] not found.

### ISSUE THREAD

**Issue by fruckt** [InfyOmLabs/adminlte-templates#83]
Hey,

Version 4.0.0 with support for laravel 9 in file [adminlte-templates]/[templates]/[scaffold]/[views]/datatable_body.stub present includes of layouts.datatables_css and layouts.datatables_js which is not present neither in adminlte-templates repository no in laravel-ui-adminlte.

Should that be fixed?

windows 10
php v8.1
Laravel v9.3.1
infyomlabs/adminlte-templates v4.0.0
infyomlabs/laravel-generator v4.0.0
infyomlabs/laravel-generator-helpers v4.0.0
infyomlabs/laravel-ui-adminlte v4.0.0

**Comment by mitulgolakiya** [comment]
@fruckt try with the latest docs with the latest version and it should be working now.

php v8.1
Laravel v9.3.1
infyomlabs/adminlte-templates v5.0.0
infyomlabs/laravel-generator v5.0.0
infyomlabs/laravel-ui-adminlte v5.0.0

Latest Docs: https://infyom.com/open-source/laravelgenerator/docs/generator-options#datatables

Feel free to re-open this issue if you are still facing a problem.
